### ISSUE TITLE
Ability to load an instance of ecore model(.xmi) file

### ISSUE THREAD

**Issue by prad20** [STARIONGROUP/EcoreNetto#4]
### Description
We tried using your library to parse an meta model made by Java EMF librray. We were able to parse the .ecore file with your library and facing issues when we try to load an instance of this model stored in a .xmi file.
We have no issues reading the ecore file, but we are wondering the capability of reading an .xmi file. Is this use case supported by your library or we have to write an extension for your library to parse the .xmi file and have an EObject as output?

### Steps to Reproduce
Load an instance of ecore file which is an .xmi file.

### System Configuration

- EcoreNetto:
Windows 10
Visual Studio 2019

**Comment by samatrhea** [comment]
Dear @prad20,

Currently we only support .ecore files, we do not support .xmi files. Can you let me know what the use case is for .xmi files in this case? My question is, why is .ecore not enough and why would you need .xmi files? That information will help me determine what a course of action can be on our side to build that support.

Regards, Sam

**Comment by samatstariongroup** [comment]
very little activity in the last couple of years, therefore it is now closed
